sudo: true
os:
  - linux
services:
  - mysql
  - redis
language: node_js
node_js:
  - "10.15.3"
before_install:
  - mysql -e 'CREATE DATABASE trans_tcc_test default character set utf8mb4 collate utf8mb4_unicode_ci;;'
  - npm i npminstall -g
install:
  - npminstall
script:
  - yarn cov
after_script:
  - npminstall codecov && codecov
cache:
  yarn: true
listen:

