sudo: false
os:
  - linux
services:
  - mysql
  - redis
language: node_js
node_js:
  - "10.15.3"
before_install:
  - mysql -e 'CREATE DATABASE trans_tcc_test;'
  - npm i npminstall -g
install:
  - npminstall
script:
  - yarn test
after_script:
  - npminstall codecov && codecov
cache:
  yarn: true

